global:
  environment: production

client:
  replicaCount: 2
  image:
    repository: shahafan/file-sharing-client
    tag: 1.0.0
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 80
  config:
    apiUrl: http://file-sharing-server:4040

server:
  replicaCount: 2
  image:
    repository: shahafan/file-sharing-server
    tag: 1.0.0
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 4040
  config:
    port: 4040
  secrets:
    postgresUser: your_user
    postgresPass: your_password
    postgresDb: file-sharing-service
    postgresHost: your-postgres-host
    awsS3Bucket: your-bucket
    awsRegion: your-region
    awsAccessKeyId: your-access-key
    awsSecretAccessKey: your-secret-key

cleanup:
  schedule: "0 * * * *"
  image:
    repository: shahafan/file-sharing-server
    tag: 1.0.0
    pullPolicy: Always

version: 0.1.1