apiVersion: v1
kind: Secret
metadata:
  name: file-sharing-server-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.server.secrets.postgresUser | b64enc }}
  POSTGRES_PASS: {{ .Values.server.secrets.postgresPass | b64enc }}
  POSTGRES_DB: {{ .Values.server.secrets.postgresDb | b64enc }}
  POSTGRES_HOST: {{ .Values.server.secrets.postgresHost | b64enc }}
  AWS_S3_BUCKET: {{ .Values.server.secrets.awsS3Bucket | b64enc }}
  AWS_REGION: {{ .Values.server.secrets.awsRegion | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.server.secrets.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.server.secrets.awsSecretAccessKey | b64enc }} 