apiVersion: v1
kind: Service
metadata:
  name: file-sharing-server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.config.port }}
      protocol: TCP
  selector:
    app: file-sharing-server 