apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-sharing-client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: file-sharing-client
  template:
    metadata:
      labels:
        app: file-sharing-client
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: {{ .Values.client.config.apiUrl }} 